### ISSUE TITLE
Set up the Development Environment

### ISSUE THREAD

**Issue by AashiqMd** [NYU-DevOps-Summer-2022/wishlists#1]
**As a** System Administrator
 **I need** to set up the Development Environment
 **So that** the agile development team can start working.
   
 ### Details and Assumptions
 * Visual Studio Coding Environment with Testing Skeleton.
 * Use template from https://github.com/nyu-devops/project-template.
 * Using a docker container with all dependencies in requirements .txt.
 * We will be using Python with Flask.
 * It should run on port 8000 by default.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a Microservice Architecture model
 When creating a new resource
 Then the developer will have a working environment to develop the code.
 ```

**Comment by AashiqMd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/1?planning-poker) with ZenHub @MDShahedurRahman @neerajkanuri

**Comment by AashiqMd** [comment]
I just saw the Professor's message:
"Since you all started from the project template repo, you don't need "... a story to set up your development environment using Visual Code Studio Remote Containers extension, to create the initial microservice skeleton" as the project template already has that."

Should we keep the story or delete it?

**Comment by MDShahedurRahman** [comment]
> I just saw the Professor's message: "Since you all started from the project template repo, you don't need "... a story to set up your development environment using Visual Code Studio Remote Containers extension, to create the initial microservice skeleton" as the project template already has that."
> 
> Should we keep the story or delete it?

We can keep it for now.
