### ISSUE TITLE
Need the ability to read the wishlist

### ISSUE THREAD

**Issue by lnv2150** [NYU-DevOps-Summer-2022/wishlists#12]
As a customer
I need to get/view my wishlist
So that I can check what is the data that is present in the wishlist

Details and Assumptions

*The server should be up and running

Acceptance Criteria

Given the customer_id
When wishlist exists for the customer_id
Then return all the products that are part of the wishlist for the customer_id

**Comment by AashiqMd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/12?planning-poker) with ZenHub @lnv2150
