### ISSUE TITLE
Need the ability to create a wishlist

### ISSUE THREAD

**Issue by MDShahedurRahman** [NYU-DevOps-Summer-2022/wishlists#2]
**As a** Customer
**I need** a way to create a wishlist
**So that** I can easily create a personalized collections of products that I want to buy and save them in my user account for future reference.

### Details and Assumptions

 - The API must be RESTful.
 - The endpoint must be called `/wishlists`.
 - When creating a wishlist, you must specify a name in the path like `/wishlists/<wishlist_name>`.
 - Duplicate names return a conflict error code.
   
 ### Acceptance Criteria  
   
```gherkin
Given the service is available
When I call create a wishlist with a particular <customer_id>
Then I would get back a wishlist of 0 product for that customer
```

**Comment by MDShahedurRahman** [comment]
I have changed 'User' to 'Customer' for the story reference.

**Comment by MDShahedurRahman** [comment]
I have updated the title to "Need the ability to create a wishlist". As per Professor, It expressed the customer's needs.

**Comment by AashiqMd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/2?planning-poker) with ZenHub @MDShahedurRahman @neerajkanuri
