### ISSUE TITLE
Create a skeleton Flask project on Github to seed starter code

### ISSUE THREAD

**Issue by MDShahedurRahman** [NYU-DevOps-Summer-2022/wishlists#3]
**As a** Developer
 **I need** some starter code
 **So that** I can start adding features to it
   
 ### Details and Assumptions
 * We will be using Python with Flask
* It should run on port `8000` by default
* It should also set up a testing skeleton as well
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there is a skeleton app
 When I issue a `git clone` on the project
 Then I should get a minimal Flask application
 When I run `python server.py`
 Then I should have a Flask server running at `localhost:8000`
 ```

**Comment by AashiqMd** [comment]
It should probably be Technical Debt and also very similar to Development Environment. Maybe I understood it wrong. Could you explain?

**Comment by MDShahedurRahman** [comment]
> 

Agreed and updated. Thanks
