### ISSUE TITLE
Need to provision a database to maintain state

### ISSUE THREAD

**Issue by MDShahedurRahman** [NYU-DevOps-Summer-2022/wishlists#4]
**As a** Developer
 **I need** to provision a database and specify the schema
 **So that** I can store the data persistently and access it.
   
 ### Details and Assumptions
 * Need to store Customer IDs
 * Need to store Wishlist name and ID.
 * Need to store Product IDs
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a database is available
 When I create, read, update, delete or list a wishlist 
 Then I should be able to access/modify the relevant data in the database. 
 ```

**Comment by neerajkanuri** [comment]
We chose the following schema for current requirements and can be extended later

**Wishlists table**

```
id
name
customer_id
```

**Wishlist - product table**

```
wishlist_id
product_id
```

We will be using a relational database

**Comment by MDShahedurRahman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/4?planning-poker) with ZenHub @AashiqMd @neerajkanuri @lnv2150

**Comment by neerajkanuri** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/4?planning-poker) with ZenHub @anugyashah01
