### ISSUE TITLE
Need the ability to update a wishlist

### ISSUE THREAD

**Issue by neerajkanuri** [NYU-DevOps-Summer-2022/wishlists#5]
**As a** customer
**I need** to update a wishlist
**So that** I can add a new product to it.

### Details and Assumptions

- customer_id is given, this refers to a customer on the `customers` microservice
- wishlist_id which already exists is given
- product_id is given, this refers to a product on the `products` microservice 

### Acceptance Criteria

```gherkin
Given the customer_id , wishlist_id and product_id
When the request for update is received
Then the product_id is added to the wishlist
```

**Comment by neerajkanuri** [comment]
Should also be able to update the name of the wishlist

**Comment by neerajkanuri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/5?planning-poker) with ZenHub @AashiqMd @MDShahedurRahman

**Comment by neerajkanuri** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/5?planning-poker) with ZenHub @neerajkanuri

**Comment by AashiqMd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wishlist-Development-629e90092e2627001a465432/issues/NYU-DevOps-Summer-2022/wishlists/5?planning-poker) with ZenHub @anugyashah01
